/**
 * TaskEasy Permission Constants
 * Every API guard checks these keys against the user's role permissions.
 */
export const PERMISSIONS = {
  // Users
  USER_CREATE: 'user.create',
  USER_READ: 'user.read',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_MANAGE_ROLES: 'user.manage-roles',

  // Projects
  PROJECT_CREATE: 'project.create',
  PROJECT_READ: 'project.read',
  PROJECT_UPDATE: 'project.update',
  PROJECT_ARCHIVE: 'project.archive',
  PROJECT_MANAGE: 'project.manage',

  // Hierarchy
  HIERARCHY_MANAGE: 'hierarchy.manage',

  // Delegation
  TASK_CREATE: 'task.create',
  TASK_ASSIGN: 'task.assign',
  TASK_READ: 'task.read',
  TASK_SUBMIT: 'task.submit',
  TASK_APPROVE: 'task.approve',
  TASK_REWORK: 'task.rework',
  TASK_DELETE: 'task.delete',
  TASK_FORCE_COMPLETE: 'task.force-complete',

  // Checklist
  CHECKLIST_ASSIGN: 'checklist.assign',
  CHECKLIST_COMPLETE: 'checklist.complete',
  CHECKLIST_MANAGE: 'checklist.manage',

  // FMS
  FMS_READ: 'fms.read',
  FMS_CREATE: 'fms.create',
  FMS_UPDATE: 'fms.update',
  FMS_DELETE: 'fms.delete',
  FMS_MANAGE: 'fms.manage',
  FMS_IMPORT: 'fms.import',
  FMS_COMPLETE: 'fms.complete',
  FMS_PUBLISH: 'fms.publish',

  // Workflow
  WORKFLOW_CREATE: 'workflow.create',
  WORKFLOW_PUBLISH: 'workflow.publish',
  WORKFLOW_DELETE: 'workflow.delete',

  // Approval
  APPROVAL_VIEW: 'approval.view',
  APPROVAL_ACTION: 'approval.action',
  APPROVAL_DELEGATE: 'approval.delegate',

  // MIS
  MIS_VIEW: 'mis.view',
  MIS_EXPORT: 'mis.export',
  MIS_SNAPSHOT: 'mis.snapshot',

  // Reports
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',
  REPORT_SCHEDULE: 'report.schedule',

  // Audit
  AUDIT_VIEW: 'audit.view',
  AUDIT_EXPORT: 'audit.export',

  // Automation
  AUTOMATION_READ: 'automation.read',
  AUTOMATION_CREATE: 'automation.create',
  AUTOMATION_UPDATE: 'automation.update',
  AUTOMATION_DELETE: 'automation.delete',
  AUTOMATION_MANAGE: 'automation.manage',

  // Forms
  FORMS_READ: 'forms.read',
  FORMS_CREATE: 'forms.create',
  FORMS_UPDATE: 'forms.update',
  FORMS_SUBMIT: 'forms.submit',
  FORMS_DELETE: 'forms.delete',

  // Settings
  SETTINGS_COMPANY: 'settings.company',
  SETTINGS_BILLING: 'settings.billing',
  SETTINGS_SECURITY: 'settings.security',

  // Bulk Import
  DELEGATION_IMPORT: 'delegation.import',
  WORK_REQUEST_IMPORT: 'workRequest.import',
  CHECKLIST_IMPORT: 'checklist.import',
  BULK_IMPORT_HISTORY: 'bulkImport.history',

  // Uploads
  UPLOAD_FILE: 'upload.file',

  // Platform console
  PLATFORM_COMPANIES_READ: 'platform.companies.read',
  PLATFORM_COMPANIES_CREATE: 'platform.companies.create',
  PLATFORM_COMPANIES_UPDATE: 'platform.companies.update',
  PLATFORM_COMPANIES_SUSPEND: 'platform.companies.suspend',
  PLATFORM_COMPANIES_IMPERSONATE: 'platform.companies.impersonate',
  PLATFORM_PLANS_MANAGE: 'platform.plans.manage',
  PLATFORM_SUBSCRIPTIONS_MANAGE: 'platform.subscriptions.manage',
  PLATFORM_BILLING_READ: 'platform.billing.read',
  PLATFORM_BILLING_UPDATE: 'platform.billing.update',
  PLATFORM_SUPPORT_MANAGE: 'platform.support.manage',
  PLATFORM_AUDIT_READ: 'platform.audit.read',
  PLATFORM_SETTINGS_MANAGE: 'platform.settings.manage',
  PLATFORM_SECURITY_MANAGE: 'platform.security.manage',
  PLATFORM_BACKUPS_MANAGE: 'platform.backups.manage',
  PLATFORM_NOTIFICATIONS_MANAGE: 'platform.notifications.manage',
  PLATFORM_REPORTS_READ: 'platform.reports.read',
  PLATFORM_USERS_MANAGE: 'platform.users.manage',
  PLATFORM_ROLES_MANAGE: 'platform.roles.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Merges a role's baseline permission set with a user's direct overrides
 * (User.permissions in the schema — extra grants on top of their role).
 *
 * This MUST be the single source of truth for "what can this user do" —
 * used both when signing the JWT at login and when re-validating the
 * token on every subsequent request (JwtStrategy). They drifted apart
 * once before: the strategy was returning only the raw direct-override
 * list, which silently 403'd every @RequirePermissions() route for
 * anyone below ADMIN.
 */
import { normalizeCompanyRole } from '../utils/role.utils';

export function resolvePermissions(role: string, directPermissions: string[] = []): string[] {
  const rolePerms = ROLE_PERMISSIONS[normalizeCompanyRole(role)] || [];
  return Array.from(new Set([...rolePerms, ...(directPermissions || [])]));
}


export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  COMPANY_OWNER: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_MANAGE_ROLES,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.PROJECT_ARCHIVE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.HIERARCHY_MANAGE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_SUBMIT,
    PERMISSIONS.TASK_APPROVE,
    PERMISSIONS.TASK_REWORK,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_FORCE_COMPLETE,
    PERMISSIONS.CHECKLIST_ASSIGN,
    PERMISSIONS.CHECKLIST_COMPLETE,
    PERMISSIONS.CHECKLIST_MANAGE,
    PERMISSIONS.FMS_READ,
    PERMISSIONS.FMS_CREATE,
    PERMISSIONS.FMS_UPDATE,
    PERMISSIONS.FMS_DELETE,
    PERMISSIONS.FMS_MANAGE,
    PERMISSIONS.FMS_IMPORT,
    PERMISSIONS.FMS_COMPLETE,
    PERMISSIONS.FMS_PUBLISH,
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_PUBLISH,
    PERMISSIONS.WORKFLOW_DELETE,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_ACTION,
    PERMISSIONS.APPROVAL_DELEGATE,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.MIS_EXPORT,
    PERMISSIONS.MIS_SNAPSHOT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_SCHEDULE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_CREATE,
    PERMISSIONS.AUTOMATION_UPDATE,
    PERMISSIONS.AUTOMATION_DELETE,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.FORMS_READ,
    PERMISSIONS.FORMS_CREATE,
    PERMISSIONS.FORMS_UPDATE,
    PERMISSIONS.FORMS_SUBMIT,
    PERMISSIONS.FORMS_DELETE,
    PERMISSIONS.DELEGATION_IMPORT,
    PERMISSIONS.WORK_REQUEST_IMPORT,
    PERMISSIONS.CHECKLIST_IMPORT,
    PERMISSIONS.BULK_IMPORT_HISTORY,
    PERMISSIONS.SETTINGS_COMPANY,
    PERMISSIONS.SETTINGS_BILLING,
    PERMISSIONS.SETTINGS_SECURITY,
    PERMISSIONS.UPLOAD_FILE,
  ],

  ADMIN: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.PROJECT_ARCHIVE,
    PERMISSIONS.TASK_CREATE,   // ADMIN must be able to create/assign delegation tasks
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_APPROVE,
    PERMISSIONS.TASK_REWORK,
    PERMISSIONS.CHECKLIST_ASSIGN,
    PERMISSIONS.CHECKLIST_MANAGE,
    PERMISSIONS.FMS_READ,
    PERMISSIONS.FMS_CREATE,
    PERMISSIONS.FMS_UPDATE,
    PERMISSIONS.FMS_MANAGE,
    PERMISSIONS.FMS_IMPORT,
    PERMISSIONS.FMS_PUBLISH,
    PERMISSIONS.FMS_COMPLETE,
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_PUBLISH,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_ACTION,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.MIS_EXPORT,
    PERMISSIONS.MIS_SNAPSHOT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    // AutomationController's GET/PATCH/DELETE routes require automation.read/
    // update/delete explicitly (PermissionsGuard does exact string matching,
    // not a "manage implies read" wildcard) — ADMIN previously only had
    // create + manage, so it could create rules but got 403'd listing,
    // viewing, editing, toggling, or deleting them.
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_CREATE,
    PERMISSIONS.AUTOMATION_UPDATE,
    PERMISSIONS.AUTOMATION_DELETE,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.DELEGATION_IMPORT,
    PERMISSIONS.WORK_REQUEST_IMPORT,
    PERMISSIONS.CHECKLIST_IMPORT,
    PERMISSIONS.BULK_IMPORT_HISTORY,
    PERMISSIONS.SETTINGS_COMPANY,
    PERMISSIONS.UPLOAD_FILE,
  ],

  MANAGER: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_APPROVE,
    PERMISSIONS.TASK_REWORK,
    PERMISSIONS.CHECKLIST_ASSIGN,
    PERMISSIONS.CHECKLIST_MANAGE,
    PERMISSIONS.FMS_READ,
    PERMISSIONS.FMS_MANAGE,
    PERMISSIONS.FMS_COMPLETE,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_ACTION,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DELEGATION_IMPORT,
    PERMISSIONS.WORK_REQUEST_IMPORT,
    PERMISSIONS.CHECKLIST_IMPORT,
    PERMISSIONS.BULK_IMPORT_HISTORY,
    PERMISSIONS.UPLOAD_FILE,
  ],

  TEAM_LEAD: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_APPROVE,
    PERMISSIONS.TASK_REWORK,
    PERMISSIONS.CHECKLIST_ASSIGN,
    PERMISSIONS.CHECKLIST_COMPLETE,
    PERMISSIONS.FMS_READ,
    PERMISSIONS.FMS_COMPLETE,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.UPLOAD_FILE,
  ],

  EMPLOYEE: [
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_SUBMIT,
    PERMISSIONS.CHECKLIST_COMPLETE,
    PERMISSIONS.FMS_READ,
    PERMISSIONS.FMS_COMPLETE,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.UPLOAD_FILE,
  ],

  AUDITOR: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.MIS_EXPORT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
  ],

  PLATFORM_ADMIN: [
    PERMISSIONS.PLATFORM_COMPANIES_READ,
    PERMISSIONS.PLATFORM_COMPANIES_CREATE,
    PERMISSIONS.PLATFORM_COMPANIES_UPDATE,
    PERMISSIONS.PLATFORM_COMPANIES_SUSPEND,
    PERMISSIONS.PLATFORM_COMPANIES_IMPERSONATE,
    PERMISSIONS.PLATFORM_PLANS_MANAGE,
    PERMISSIONS.PLATFORM_SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.PLATFORM_BILLING_READ,
    PERMISSIONS.PLATFORM_BILLING_UPDATE,
    PERMISSIONS.PLATFORM_SUPPORT_MANAGE,
    PERMISSIONS.PLATFORM_AUDIT_READ,
    PERMISSIONS.PLATFORM_SETTINGS_MANAGE,
    PERMISSIONS.PLATFORM_SECURITY_MANAGE,
    PERMISSIONS.PLATFORM_BACKUPS_MANAGE,
    PERMISSIONS.PLATFORM_NOTIFICATIONS_MANAGE,
    PERMISSIONS.PLATFORM_REPORTS_READ,
    PERMISSIONS.PLATFORM_USERS_MANAGE,
    PERMISSIONS.PLATFORM_ROLES_MANAGE,
  ],

  SUPPORT_AGENT: [
    PERMISSIONS.PLATFORM_COMPANIES_READ,
    PERMISSIONS.PLATFORM_SUPPORT_MANAGE,
    PERMISSIONS.PLATFORM_AUDIT_READ,
    PERMISSIONS.PLATFORM_REPORTS_READ,
    PERMISSIONS.PLATFORM_NOTIFICATIONS_MANAGE,
  ],

  BILLING_MANAGER: [
    PERMISSIONS.PLATFORM_COMPANIES_READ,
    PERMISSIONS.PLATFORM_PLANS_MANAGE,
    PERMISSIONS.PLATFORM_SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.PLATFORM_BILLING_READ,
    PERMISSIONS.PLATFORM_BILLING_UPDATE,
    PERMISSIONS.PLATFORM_REPORTS_READ,
  ],

  SALES_MANAGER: [
    PERMISSIONS.PLATFORM_COMPANIES_READ,
    PERMISSIONS.PLATFORM_COMPANIES_CREATE,
    PERMISSIONS.PLATFORM_PLANS_MANAGE,
    PERMISSIONS.PLATFORM_NOTIFICATIONS_MANAGE,
    PERMISSIONS.PLATFORM_REPORTS_READ,
  ],

  PLATFORM_AUDITOR: [
    PERMISSIONS.PLATFORM_COMPANIES_READ,
    PERMISSIONS.PLATFORM_BILLING_READ,
    PERMISSIONS.PLATFORM_AUDIT_READ,
    PERMISSIONS.PLATFORM_REPORTS_READ,
  ],

  VIEWER: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.MIS_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ],
};
